[profile.default]
src = "src"
out = "out"
libs = ["lib"]
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
scroll = "https://sepolia-rpc.scroll.io"
vanar = "https://rpc-vanguard.vanarchain.com"